[tool.black]
line-length = 89

[tool.isort]
filter_files = true
force_single_line = true
line_length = 89
profile = "black"

# pyproject.toml
[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore::statsmodels.tools.sm_exceptions.DomainWarning", # due to fitting the dipersion curve with the identity link
]

[tool.mypy]
exclude = '^(tests/|docs/source/conf.py|example|venv/|setup.py)'
check_untyped_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_untyped_decorators = true
disallow_incomplete_defs = true
plugins = "numpy.typing.mypy_plugin"
